### ISSUE TITLE
Connection pool is full, discarding connection: localhost in 2.17.0

### ISSUE THREAD

**Issue by bedge** [requests/requests#4101]
Summary.

After upgrading to 2.17.0 (from 2.14.2) I got an immediate failure on all apps using the requests lib.

Given the fact that no one else has seen this, I expect it's an incompatibility between other libs. 
Filing here first to track.

## Expected Result

No exception in normal use case.

What you expected.

No exception in normal use case.

## Actual Result

```
u'25177330-cf2a-3943-af3b-86582902a2cc', u'f296a708-e02c-393, resp:None, <type 'exceptions.ValueError'> Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
Traceback (most recent call last):
  File "/opt/nim/ur-api/mlutil/sdk/nimsdk.py", line 154, in _GET
    params=arguments
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
```

What happened instead.

See exception above

## Reproduction Steps

Have not tried to isolate or narrow focus. 

## System Information

    $ python -m requests.help

```
ubuntu@ip-10-200-17-89:~$ python --version
Python 2.7.12
ubuntu@ip-10-200-17-89:~$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Thanks for taking the time to open this ticket, @bedge. I've got a feeling this is related to the unvendoring of Requests' dependencies. It looks like this *should* be solved in 2.17.1. Would you mind upgrading before we continue debugging here?

**Comment by bedge** [comment]
Confirmed fixed in:
```
requests==2.17.3
```
Thanks for the rapid response.

**Comment by kennethreitz** [comment]
\o/
