### ISSUE TITLE
UnicodeDecodeError in requests.get(url) method

### ISSUE THREAD

**Issue by zhuifengshen** [requests/requests#4122]
## Code: test.py
```
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
import requests
url = 'http://www.yftxt.com/plus/xiazai_yfx.php?open=2&id=12914&uhash=7fadfdb165fadc7362f9dc90'
requests.get(url)
```

## System Information
ubuntu 16.04
python3.6.1
requests2.14.2

## Run
$ python test.py

## Result
```
Traceback (most recent call last):
  File "/home/devin/Project/github/pythonic/Py3Demo/demo.py", line 71, in <module>
    requests.get(url)
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 661, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 661, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 122, in resolve_redirects
    url = self.get_redirect_target(resp)
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 113, in get_redirect_target
    return to_native_string(location, 'utf8')
  File "/usr/local/lib/python3.6.1/lib/python3.6/site-packages/requests/_internal_utils.py", line 25, in to_native_string
    out = string.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 39: invalid start byte
```

##Help
Does anyone knows this problem? Thanks

**Comment by StewPoll** [comment]
Looks like the redirect location isn't encoded correct. Try it with
`allow_redirects=false` and look at the response's `Location` header

**Comment by zhuifengshen** [comment]
@TetraEtc thank you for your help to solve my problem^&^
