### ISSUE TITLE
Can't parse version information, urllib3 returns "['dev']"

### ISSUE THREAD

**Issue by Ichicoro** [requests/requests#4143]
I wrote a script and tried to execute it. The python interpreter stopped the execution with a traceback saying that
```
Traceback (most recent call last):
  File ".\main.py", line 3, in <module>
    import lyricsgetter
  File "C:\Users\smart\Documents\Projects\telegram-lyrics-bot\lyricsgetter.py", line 1, in <module>
    import requests
  File "C:\Users\smart\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\__init__.py", line 53, in <module>
    major, minor, patch = urllib3_version
ValueError: not enough values to unpack (expected 3, got 1)
```
I then tried adding a `print(urllib3_version)` before line 53 in `__init__.py`. 

## Expected Result

`print(urllib3_version)` should have returned the version, and my script should have executed fine.

## Actual Result

`print(urllib3_version)` printed `['dev']` and stopped the execution of my script with a `ValueError`

## Reproduction Steps

```python
import requests
```

## System Information

    $ python -m requests.help

```
['1', '21', '1']          
{                         
  "chardet": {            
    "version": "3.0.4"    
  },                      
  "cryptography": {       
    "version": ""         
  },                      
  "implementation": {     
    "name": "CPython",    
    "version": "3.6.0"    
  },                      
  "platform": {           
    "release": "10",      
    "system": "Windows"   
  },                      
  "pyOpenSSL": {          
    "openssl_version": "",
    "version": null       
  },                      
  "requests": {           
    "version": "2.17.3"   
  },                      
  "system_ssl": {         
    "version": "100020af" 
  },                      
  "urllib3": {            
    "version": "1.21.1"   
  },                      
  "using_pyopenssl": false
}                         
```

**Comment by sigmavirus24** [comment]
That's quite fascinating especially given the output of `python -m requests.help` as you printed it which shows `urllib3` at version 1.21.1 and even `urllib3_version` as `['1', '21', '1']`.

**Comment by nateprewitt** [comment]
Hey @Ichicoro, this is actually a duplicate of #4076. I'm in the process of finishing a PR to address this so it should be fixed in an upcoming release. Thanks for taking the time to make sure this was documented.

**Comment by sigmavirus24** [comment]
Can you share any of your code in the traceback?

@nateprewitt this is related but different I think

**Comment by nateprewitt** [comment]
`telegram-lyrics-bot` is using `python-telegram-bot` which vendors a custom version of urllib3. The vendored version has a `__version__` of `dev` which is what's causing this.

**Comment by Ichicoro** [comment]
@sigmavirus24 Do you mean the code from my install of `requests` or from my project?

**Comment by sigmavirus24** [comment]
Ah I see @nateprewitt. @Ichicoro, @nateprewitt is in fact correct that this is a duplicate.

**Comment by fuuman** [comment]
I am also getting this error at the moment. I don't understand why there is defintly urllib3 in version 1.21.1 installed, but in my code requests wants to import urllib3 in version ['dev']. I just don't get it. There is just one version of urllib3 installed in my virtualenv.

**Comment by Lukasa** [comment]
@fuuman Are you using anything that patches or overrides urllib3, e.g. `telegram`?

**Comment by fuuman** [comment]
Yeah, I am using the [python-telegram-bot wrapper](https://github.com/python-telegram-bot/python-telegram-bot).

**Comment by Lukasa** [comment]
@fuuman Ok, see #4076, which reveals that telegram is aliasing your copy of urllib3.
