### ISSUE TITLE
r.text on JavaScript file with no explicit encoding hangs indefinitely

### ISSUE THREAD

**Issue by nyuszika7h** [requests/requests#4235]
When I request https://play.wimpmusic.com/v1.1.3-p-40/app.js and then try to use `r.text` without setting `r.encoding`, my script hangs indefinitely instead of returning the text or raising an exception. `r.content` works fine, and as soon as I set `r.encoding = 'utf-8'` or anything, `r.text` also works. The `Content-Type` header the site is returning is `application/x-javascript` (no encoding specificed).

## Reproduction Steps

```python3
import requests
r = requests.get('https://play.wimpmusic.com/v1.1.3-p-40/app.js')
print(r.text)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "4.4.0-43-Microsoft",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.3"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by Lukasa** [comment]
How big is the file? If you ctrl+c the code while running indefinitely, what traceback do you see?

**Comment by ghost** [comment]
It's about 1.31 MiB. This is the traceback I get when interrupting it after about 10 seconds:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/requests/models.py", line 852, in text
    encoding = self.apparent_encoding
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/requests/models.py", line 722, in apparent_encoding
    return chardet.detect(self.content)['encoding']
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/chardet/__init__.py", line 38, in detect
    detector.feed(byte_str)
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/chardet/universaldetector.py", line 211, in feed
    if prober.feed(byte_str) == ProbingState.FOUND_IT:
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/chardet/charsetgroupprober.py", line 71, in feed
    state = prober.feed(byte_str)
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/chardet/sbcharsetprober.py", line 79, in feed
    byte_str = self.filter_international_words(byte_str)
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/chardet/charsetprober.py", line 87, in filter_international_words
    buf)
  File "/usr/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
KeyboardInterrupt

```

**Comment by Lukasa** [comment]
Ok, so this seems slow even for chardet. @sigmavirus24, why is chardet so slow here?

**Comment by ghost** [comment]
Okay, I left it running a bit longer. Looks like it takes about 66.26 seconds on my computer, and 8.76 seconds on a more powerful server.

**Comment by bakert** [comment]
Same problem here with `https://archive.scryfall.com/json/scryfall-default-cards.json` which is a large JSON file sent back with `content-type: application/json`.

(Setting `response.encoding = 'utf-8'` explicitly makes things take milliseconds not minutes.)

**Comment by nateprewitt** [comment]
This class of slow downs were possible in chardet, but there isn't a great way to resolve them in Requests. Given `chardet` was replaced by `charset_normalizer` as the default, and this issue is no longer reproducible, I'm going to close.
