### ISSUE TITLE
Recieving 400 Bad Request on PUT against Ranger API 

### ISSUE THREAD

**Issue by mtdeguzis** [requests/requests#4268]
Summary.

Submitting a PUT request against the Ranger API: https://cwiki.apache.org/confluence/display/RANGER/REST+APIs+for+Policy+Management#RESTAPIsforPolicyManagement-UpdatePolicy. I can create the policy fine, but seems with PUT, I get bad request and cannot determine why.

Headers on GET
```
Retrieving and exporting policy 16: <POLICY_NAME>
{'transfer-encoding': 'chunked', 'set-cookie': 'RANGERADMINSESSIONID=<ID>; Path=/; HttpOnly, hadoop.auth=; Path=/; Domain=HOST.DOMAIN.COM; Expires=Thu, 01-Jan-1970 00:00:00 GMT; HttpOnly', 'server': 'Apache-Coyote/1.1', 'date': 'Tue, 29 Aug 2017 14:57:25 GMT', 'x-frame-options': 'DENY', 'content-type': 'application/json', 'www-authenticate': 'Negotiate'}
```

Headers on successful POST
```

{'transfer-encoding': 'chunked', 'set-cookie': 'RANGERADMINSESSIONID=<ID>; Path=/; HttpOnly, hadoop.auth=; Path=/; Domain=HOST.DOMAIN.COM; Expires=Thu, 01-Jan-1970 00:00:00 GMT; HttpOnly', 'server': 'Apache-Coyote/1.1', 'date': 'Tue, 29 Aug 2017 15:34:04 GMT', 'x-frame-options': 'DENY', 'content-type': 'application/json', 'www-authenticate': 'Negotiate'}
Policy applied <POLICY_NUM>
```

Headers on PUT (400 respose)
```
Submitting PUT API request: http://HOST:PORT/service/public/api/policy/<POLICY_NUM>
{'transfer-encoding': 'chunked', 'set-cookie': 'RANGERADMINSESSIONID=<ID>; Path=/; HttpOnly, hadoop.auth=; Path=/; Domain=HOST.DIOMAIN.COM; Expires=Thu, 01-Jan-1970 00:00:00 GMT; HttpOnly', 'server': 'Apache-Coyote/1.1', 'connection': 'close', 'date': 'Tue, 29 Aug 2017 15:19:58 GMT', 'x-frame-options': 'DENY', 'content-type': 'application/json', 'www-authenticate': 'Negotiate'}
```

The object exists at the endpoint, so a PUT needs made.

## Expected Result

Response code 200

What you expected.

## Actual Result

```
Traceback (most recent call last):
  File "ranger-policy-manager.py", line 183, in <module>
    result.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request
```

## Reproduction Steps

Hard to reproduce without a Hadoop Ranger environement.

**Comment by Lukasa** [comment]
400 bad request generally suggests that this is a problem with your data not matching what Hadoop wants. Without knowing what that looks like, I'm afraid we simply cannot help you.
