### ISSUE TITLE
Stop Requests.post from encoding the data field,

### ISSUE THREAD

**Issue by realoriginal** [requests/requests#4298]
Hello,

I was wondering if it it is possible to stop requests from encoding the data field in a post request?

**Comment by ghost** [comment]
I guess im saying in request body, in a post request.

**Comment by Lukasa** [comment]
Yes: just pass a string, not a dictionary.

**Comment by ghost** [comment]
You mean data="cmd = blah"

**Comment by Lukasa** [comment]
Yes.

**Comment by ghost** [comment]
Just did that, getting 
```python
Traceback (most recent call last):
  File "command_php_exec_noauth.py", line 9, in <module>
    req = requests.post("http://{}:{}/command.php".format(args.target, args.port), data="cmd = ls -alt")
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by ghost** [comment]
Just did that, getting 
```python
Traceback (most recent call last):
  File "command_php_exec_noauth.py", line 9, in <module>
    req = requests.post("http://{}:{}/command.php".format(args.target, args.port), data="cmd = ls -alt")
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by Lukasa** [comment]
That means the server is closing the connection in our face. Suggests a problem in the server code.

**Comment by ghost** [comment]
Strange, shouldnt be if im essentially able to send the equivalent of this with curl and it works fine.

**Comment by ghost** [comment]
I take it its not possible to disable URL encoding for the data field?

**Comment by Lukasa** [comment]
Only using the method I mentioned.
