### ISSUE TITLE
Typo in path? ""Could not find suitable TLS certificate

### ISSUE THREAD

**Issue by niderhoff** [requests/requests#4354]
Due to what I susped to be a TYPO in a hard-coded PATH in the requests package, the certificate is not found in Windows 10.

Requests Version is 2.14.2 from anaconda 4.4.0 for Windows 64bit.

## Expected Result

Pip/Conda work using TLS.

## Actual Result

``
`$ C:\Users\niid\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\adapters.py", line 405, in send
        self.cert_verify(conn, request.url, verify, cert)
      File "C:\Users\niid\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\adapters.py", line 225, in cert_verify
        "invalid path: {0}".format(cert_loc))
    IOError: Could not find a suitable TLS CA certificate bundle, invalid path: %SystemRoom%\System32\cacert.pem
``

Notice *SystemRoom* instead of *SystemRoot* in the last line.

## Reproduction Steps

```
conda update conda

```

**Comment by niderhoff** [comment]
Okay, something messed up my system environment variables. Never mind.
