### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'create_connection'

### ISSUE THREAD

**Issue by zhangxu3486432** [requests/requests#4473]
manjaro python3.6 
requests==2.18.4
PyMySQL==0.8.0
urllib3==1.22
certifi==2017.11.5
chardet==3.0.4
idna==2.5
six==1.11.0

import requests
req = requests.get('https://www.baidu.com')

------------------------------------------------error-----------------------------------------------------------

```
Traceback (most recent call last):
  File "/home/zhangxu/project/python/map/test.py", line 1, in <module>
    import requests
  File "/home/zhangxu/.virtualenvs/spider/lib/python3.6/site-packages/requests/__init__.py", line 48, in <module>
    import urllib3
  File "/home/zhangxu/.virtualenvs/spider/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/zhangxu/.virtualenvs/spider/lib/python3.6/site-packages/urllib3/connectionpool.py", line 7, in <module>
    from socket import error as SocketError, timeout as SocketTimeout
  File "/usr/lib64/python3.6/socket.py", line 52, in <module>
    import os, sys, io, selectors
  File "/usr/lib64/python3.6/selectors.py", line 11, in <module>
    import select
  File "/home/zhangxu/project/python/map/select.py", line 31, in <module>
    con = connect.mysql_save()
  File "/home/zhangxu/project/python/map/connect.py", line 7, in __init__
    self.conn = self.connect()
  File "/home/zhangxu/project/python/map/connect.py", line 16, in connect
    conn = pymysql.connect(host=host, port="", user=user, passwd=password, db=dbName, charset=charset)
  File "/home/zhangxu/.virtualenvs/spider/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/home/zhangxu/.virtualenvs/spider/lib/python3.6/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/home/zhangxu/.virtualenvs/spider/lib/python3.6/site-packages/pymysql/connections.py", line 918, in connect
    sock = socket.create_connection(
AttributeError: module 'socket' has no attribute 'create_connection'
```

**Comment by sigmavirus24** [comment]
You have a file called `select.py` that you've placed in your import path. When the standard library tries to import the stdlib `select` it gets yours and this is why you're seeing this issue.

This is not a bug in requests. If you need further assistance, please post a question on [StackOverflow](https://stackoverflow.com).
