### ISSUE TITLE
cannot import name set_file_position  

### ISSUE THREAD

**Issue by ror6ax** [requests/requests#4502]
Summary.

## Expected Result

```
python > import requests > working 
```

## Actual Result

```
$ python                                       
Python 2.7.14 (default, Dec 11 2017, 16:08:01)                                                 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2                                               
Type "help", "copyright", "credits" or "license" for more information.                         
>>> import requests                            
Traceback (most recent call last):             
  File "<stdin>", line 1, in <module>          
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>           
    from .packages.urllib3.exceptions import DependencyWarning                                 
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>  
    import urllib3                             
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>             
    from .connectionpool import (              
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 39, in <module>      
    from .util.request import set_file_position                                                
ImportError: cannot import name set_file_position    
```
## Reproduction Steps

```python
import requests
```

## System Information
```
    $ $ python -m requests.help
/usr/bin/python: cannot import name set_file_position
```

**Comment by nateprewitt** [comment]
@ror6ax [set_file_position](https://github.com/shazow/urllib3/blob/d9898fb39e6c6037dea12d7226813d35b40f0947/urllib3/util/request.py#L77) definitely exists in urllib3. It appears you have an outdated version of urllib3, so I suggest updating to 1.22.

Since this seems to be a request for help rather than a defect in Requests, can you please open a question on [StackOverflow](https://www.stackoverflow.com) with any further questions and we can look at getting things resolved there. Thanks!
