### ISSUE TITLE
I am unable to run tests on threedotoh branch.

### ISSUE THREAD

**Issue by RatanShreshtha** [requests/requests#4528]
I am unable to run tests on threedotoh branch.

## Expected Result

Al tests should pass.

## Actual Result
```
Traceback (most recent call last):
  File "/home/rkulshreshtha/.local/share/virtualenvs/requests-mRwENnZg/lib/python3.6/site-packages/_pytest/config.py", line 329, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/rkulshreshtha/Desktop/foss/requests/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rkulshreshtha/.local/share/virtualenvs/requests-mRwENnZg/lib/python3.6/site-packages/_pytest/config.py", line 360, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/rkulshreshtha/Desktop/foss/requests/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rkulshreshtha/.local/share/virtualenvs/requests-mRwENnZg/lib/python3.6/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/rkulshreshtha/.local/share/virtualenvs/requests-mRwENnZg/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/home/rkulshreshtha/.local/share/virtualenvs/requests-mRwENnZg/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/rkulshreshtha/Desktop/foss/requests/tests/conftest.py", line 4, in <module>
    from requests.compat import urljoin
ImportError: cannot import name 'urljoin'
ERROR: could not load /home/rkulshreshtha/Desktop/foss/requests/tests/conftest.py
```
## Reproduction Steps

```bash
$ git checkout threedotoh
$ pipenv --three
$ pipenv shell
$ pipenv install --dev
$ py.test
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "4.15.4-300.fc27.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "3.0.0"
  },
  "system_ssl": {
    "version": "1010007f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by kennethreitz** [comment]
it is being worked on :)

**Comment by kennethreitz** [comment]
Check out the 3.0 branch, tests are passing there.

**Comment by RatanShreshtha** [comment]
thanks, @kennethreitz  so is 3.0 branch will be used for further development?

And I would like to help in type annotation the library how I should proceed?

**Comment by kennethreitz** [comment]
@RatanShreshtha send pull requests to that branch!

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
That is the current working plan.
