### ISSUE TITLE
Incompatibility with CX-Freeze and PyInstaller

### ISSUE THREAD

**Issue by dcsoft4** [requests/requests#4561]
As reported on [StackOverflow](https://stackoverflow.com/a/41718977/2073217), the latest Requests version dies on initialization in an app frozen app by CX-Freeze / PyInstaller.  But Requests version 2.11.1 works OK. 

## Expected Result

The current versions of Requests run without exception,  like version 2.11.1 does.

## Actual Result

This exception occurred:

Traceback (most recent call last):
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "PythonSocketIoClient.py", line 5, in <module>
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\socketIO_client\__init__.py", line 14, in <module>
    from .transports import (
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\socketIO_client\transports.py", line 1, in <module>
    import requests
  **File "C:\PythonEnvs\CL\Client32\lib\site-packages\requests\__init__.py", line 98, in <module>**
    from . import packages
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\requests\packages.py", line 7, in <module>
    locals()[package] = __import__(package)
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\idna\__init__.py", line 2, in <module>
    from .core import *
  File "C:\PythonEnvs\CL\Client32\lib\site-packages\idna\core.py", line 1, in <module>
    from . import idnadata
**ImportError: cannot import name 'idnadata'**

## Reproduction Steps

Run CX-Freeze (or PyInstaller) with the appropriate Requests version installed, to compare the results.

## System Information

{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

**Comment by nateprewitt** [comment]
Hi @dcsoft4, this is either an issue with your local installation or PyInstaller. It can’t find resources for idna which are a requirement for modern versions of Requests. Ensure you have idna installed properly and see if that fixes the issue.

In the future, please route questions for assistance to [StackOverflow](https://stackoverflow.com) with the python-requests tag. We’re happy to follow up over there. We try to keep the issue tracker solely for defects in Requests which this doesn’t appear to be. Thanks!

**Comment by sigmavirus24** [comment]
There are also numerous examples of other issues which are already closed and solved to research. Please always search closed issues before opening new ones.
