### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by SG5** [requests/requests#4567]
I have same issue from #4367 
```
Exception ignored in: <generator object urlsplit.<locals>.<genexpr> at 0x1087bdca8>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 431, in <genexpr>
    if not rest or any(c not in '0123456789' for c in rest):
SystemError: error return without exception set
Exception ignored in: <generator object urlsplit.<locals>.<genexpr> at 0x108788830>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 431, in <genexpr>
    if not rest or any(c not in '0123456789' for c in rest):
SystemError: error return without exception set
Exception ignored in: <generator object urlsplit.<locals>.<genexpr> at 0x108788360>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 431, in <genexpr>
    if not rest or any(c not in '0123456789' for c in rest):
SystemError: error return without exception set
Exception ignored in: <generator object iter_slices at 0x108788360>
Traceback (most recent call last):
  File "~/.venv/lib/python3.6/site-packages/requests/utils.py", line 449, in iter_slices
    def iter_slices(string, slice_length):
SystemError: error return without exception set
Exception ignored in: <generator object urlsplit.<locals>.<genexpr> at 0x1095fffc0>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 431, in <genexpr>
    if not rest or any(c not in '0123456789' for c in rest):
SystemError: error return without exception set
Exception ignored in: <generator object iter_slices at 0x1095ffba0>
Traceback (most recent call last):
  File "~/.venv/lib/python3.6/site-packages/requests/utils.py", line 449, in iter_slices
    def iter_slices(string, slice_length):
SystemError: error return without exception set
```

It happens when I make requests in many `threading.Thread`

**Comment by sigmavirus24** [comment]
As mentioned in #4367, this is not something that Requests controls. This is almost certianly coming from a library used at some point in the execution of the program (e.g., `json`) that has a C dependency and the threading is leading to this issue. There's nothing for Requests to do as far as we can tell with all of the given information we have.

**Comment by fhlee74** [comment]
Have anyone figured out how to fix this issue?

**Comment by jimas14** [comment]
@fhlee74 I seem to have fixed this issue by running my script in a 2.7 env instead of 3.6. The issue did seem to be worse when running > 1 threads in 3.6 but would still happen with just one thread. On 2.7 I have 10 threads running again and haven't seen the exception.

**Comment by FireKAKA** [comment]
threads are tooooooooooooooooooooooooooooooooooooooooooooooo many ! This is a python's BUG, whether in 2.7 or 3.6 . You can try to use threads pool `from multiprocessing.pool import ThreadPool` . I have 8 threads running and no exception is thrown on 3.6.

**Comment by romanbarabash** [comment]
this helped me with python 3.7.3 and pycharm https://stackoverflow.com/a/52054289

**Comment by aulorbe** [comment]
This worked for me too ^
