### ISSUE TITLE
import requests throws ValueError on urllib3.__version__.split

### ISSUE THREAD

**Issue by synhershko** [requests/requests#4645]
It may be an environment issue but I keep reproducing this error with latest requests:

```
➜  python3
Python 3.6.5 (default, Mar 30 2018, 06:41:53)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/requests/__init__.py", line 49, in <module>
    major, minor, patch = urllib3.__version__.split('.')[:3]
ValueError: not enough values to unpack (expected 3, got 2)
```

Here is a snip from `pip3 freeze`:

```
requests==2.18.4
requests2==2.16.0
rsa==3.4.2
urllib3==1.22
```

Please advise

**Comment by synhershko** [comment]
Was due to version clashes which I just was able to fix, closing
