### ISSUE TITLE
KeyError with Instabot on python 2.7.15 for mac

### ISSUE THREAD

**Issue by hamadberlin** [requests/requests#4658]
hey guys,

i'm really trying to fix that problem and did research on internet but im not able to finde the  selution.

can someone help me? *please *freshman

MacBook-Air:instabot.py-master2 XXX$ python example.py
23.05.2018_16:30 Instabot v1.2.0 started at 23.05.2018 16:30:

23.05.2018_16:30 Trying to login as XXXX...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/XXX/Desktop/instabot.py-master2/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/XXX/Desktop/instabot.py-master2/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by hamadberlin** [comment]
solution here: https://github.com/instabot-py/instabot.py/issues/1287

CLOSED
