### ISSUE TITLE
Exceptions when using data=json.dumps(payload))

### ISSUE THREAD

**Issue by redstoneleo** [requests/requests#4745]
```
import json , requests 
r = requests.post(
      "http://httpbin.org/post",
      files={'image': open(filename, 'rb')},
      data=json.dumps({'wordPos': [86, 23]})
  )

```

**exceptions:** 

```
Traceback (most recent call last):
  File "D:\BaiduYunDownload\编程\Python\Project\EngkuDict\Utils.py", line 128, in <module>
    myOCR2()
  File "D:\BaiduYunDownload\编程\Python\Project\EngkuDict\Utils.py", line 116, in myOCR2
    data=json.dumps({'wordPos': [86, 23]})
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 312, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 500, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Users\i\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 122, in _encode_files
    raise ValueError("Data must not be a string.")
ValueError: Data must not be a string.
```

**Comment by nateprewitt** [comment]
@redstoneleo it's not clear how you would be hitting this code path. `_encode_files` is only triggered when the `files` parameter isn't False-y. The code you've provided doesn't seem to reproduce the issue either.

We'll need the information we initially asked for with this issue in order to do any further debugging, but at first glance, this looks like a local misconfiguration.

**Comment by redstoneleo** [comment]
@nateprewitt Sorry for that , I've updated the test code

**Comment by nateprewitt** [comment]
@redstoneleo, if you're passing both data and files, they need to be key-value pairs. When you serialize the dictionary into a string with `json.dumps` we lose the semantics of the dictionary and can't map to multipart/form-data correctly.

If you remove the `json.dumps` portion, things should work as expected.

**Comment by redstoneleo** [comment]
Thanks, as far as I know , the documentation has not covered what you have said, it would be better to add in it.
BTW, since  `data` could accept `json.dumps()`, while `json.dumps()` is a `str `object , but [the doc](http://docs.python-requests.org/en/master/api/#requests.Response) has not mentioned the `data` parameter could accept  a `str `object, so I think this should also be added in 

The current description for `data` parameter 
> data – (optional) Dictionary, list of tuples, bytes, or file-like object to send in the body of the Request.
