### ISSUE TITLE
bdist_wheel upload failes for python3

### ISSUE THREAD

**Issue by thilo-maurer** [requests/requests#4752]
Cannot upload wheel using python3.

Reason is that in this projects's `setup.py` line 86, argument `classifiers` should be an array, not a tuple. Replacing `(` by `[` fixes the issue.

## Expected Result
Success for
```python3 setup.py bdist_wheel upload -r artifactory```

## Actual Result
```
root@host:/build/requests-2.19.1.tar.gz.extracted/requests-2.19.1# python3 setup.py bdist_wheel upload -r artifactory
running bdist_wheel
running build
running build_py
running egg_info
writing requests.egg-info/PKG-INFO
writing dependency_links to requests.egg-info/dependency_links.txt
writing requirements to requests.egg-info/requires.txt
writing top-level names to requests.egg-info/top_level.txt
reading manifest file 'requests.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'NOTICE'
warning: no files found matching 'requirements.txt'
writing manifest file 'requests.egg-info/SOURCES.txt'
installing to build/bdist.linux-ppc64le/wheel
running install
running install_lib
creating build/bdist.linux-ppc64le/wheel
creating build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/_internal_utils.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/certs.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/exceptions.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/compat.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/auth.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/structures.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/packages.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/hooks.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/adapters.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/utils.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/api.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/sessions.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/__init__.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/__version__.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/models.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/help.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/status_codes.py -> build/bdist.linux-ppc64le/wheel/requests
copying build/lib/requests/cookies.py -> build/bdist.linux-ppc64le/wheel/requests
running install_egg_info
Copying requests.egg-info to build/bdist.linux-ppc64le/wheel/requests-2.19.1-py3.6.egg-info
running install_scripts
creating build/bdist.linux-ppc64le/wheel/requests-2.19.1.dist-info/WHEEL
creating '/build/requests-2.19.1.tar.gz.extracted/requests-2.19.1/dist/requests-2.19.1-py2.py3-none-any.whl' and adding '.' to it
adding 'requests/__init__.py'
adding 'requests/__version__.py'
adding 'requests/_internal_utils.py'
adding 'requests/adapters.py'
adding 'requests/api.py'
adding 'requests/auth.py'
adding 'requests/certs.py'
adding 'requests/compat.py'
adding 'requests/cookies.py'
adding 'requests/exceptions.py'
adding 'requests/help.py'
adding 'requests/hooks.py'
adding 'requests/models.py'
adding 'requests/packages.py'
adding 'requests/sessions.py'
adding 'requests/status_codes.py'
adding 'requests/structures.py'
adding 'requests/utils.py'
adding 'requests-2.19.1.dist-info/LICENSE.txt'
adding 'requests-2.19.1.dist-info/top_level.txt'
adding 'requests-2.19.1.dist-info/WHEEL'
adding 'requests-2.19.1.dist-info/METADATA'
adding 'requests-2.19.1.dist-info/RECORD'
removing build/bdist.linux-ppc64le/wheel
running upload
Traceback (most recent call last):
  File "setup.py", line 106, in <module>
    'socks:sys_platform == "win32" and (python_version == "2.7" or python_version == "2.6")': ['win_inet_pton'],
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```
## Reproduction Steps
After
```
pip3 download requests --no-binary :all:
```
then extracting the package, then
* build good
* upload failes, when using python3 (python2 is fine)

**Comment by nateprewitt** [comment]
Hi @thilo-maurer, this should be resolved in 489f58ce. Thanks for the report!
