### ISSUE TITLE
Not supported proxy scheme error

### ISSUE THREAD

**Issue by oshadaamila** [requests/requests#4797]
I am conecting to the internet through a proxy server. I used the below code to send a HTTP GET request using _requests_ library in python.

   ```
 import requests
    from requests.auth import HTTPProxyAuth
    
    url = "http://httpbin.org/get" 
    proxies = {"http":"my-proxy-server: port"}
    auth = HTTPProxyAuth("username", "password")
    r = requests.get(url, proxies=proxies, auth=auth)
    print r
```

but It gives me the following error

   ```
 Traceback (most recent call last):
      File "D:\python_http_req.py", line 7, in <module>
        r = requests.get(url, proxies=proxies, auth=auth)
      File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
        return request('get', url, params=params, **kwargs)
      File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
        return session.request(method=method, url=url, **kwargs)
      File "C:\Python27\lib\site-packages\requests\sessions.py", line 512, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Python27\lib\site-packages\requests\sessions.py", line 622, in send
        r = adapter.send(request, **kwargs)
      File "C:\Python27\lib\site-packages\requests\adapters.py", line 410, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\Python27\lib\site-packages\requests\adapters.py", line 308, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "C:\Python27\lib\site-packages\requests\adapters.py", line 198, in proxy_manager_for
        **proxy_kwargs)
      File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 449, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 400, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    ProxySchemeUnknown: Not supported proxy scheme my-proxy-server

```
can anybody help me to resolve this error?

**Comment by oshadaamila** [comment]
It was a issue in my proxy server

**Comment by Sadaananth** [comment]
i too have this issue..can you please share me how did you resolve it?

**Comment by samiashton1989** [comment]
i too have this issue..can you please share me how did you resolve it?

**Comment by samiashton1989** [comment]
from requests.auth import HTTPProxyAuth
proxyDict = {
          'http'  : 'http://138.197.222.35:80',
          'https' : 'http://1138.197.222.35:8080'
        }
        #auth = HTTPProxyAuth('username', 'mypassword')
        r = requests.get('http://httpbin.org/ip', proxies=proxyDict)
        print (r)

**Comment by searchformyusername** [comment]
@oshadaamila This issue is resolved with solution by @samiashton1989 Consider it closing.
