### ISSUE TITLE
SSLError: [Errno 8] _ssl.c:508: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by msuthar291086** [requests/requests#4807]
Hi Experts,

I am getting the following error while running a python script on my Linux box.

Script: https://github.com/coreyhines/Arista/blob/master/bugalertUpdate.py

Traceback (most recent call last):
  File "./bugalertUpdate-2.py", line 84, in <module>
    result = requests.post(url, data=json.dumps(jsonpost))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 331, in send
    raise SSLError(e)
SSLError: [Errno 8] _ssl.c:508: EOF occurred in violation of protocol

Request your help on this issue.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
