### ISSUE TITLE
Running prepare_headers on PreparedRequest break it

### ISSUE THREAD

**Issue by mlubimow** [requests/requests#4833]
After calling prepare() on a request, PreparedRequest object is returned. If its a PATCH request (GET is working as expected), and prepare_headers is called, it's not possible to send this request.

## Expected Result

Headers should be added to a prepared request and it should be possible to send it later.

## Actual Result

An exception is thrown:

```
Traceback (most recent call last):
  File "r.py", line 7, in <module>
    s.send(r)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 466, in send
    low_conn.send(hex(len(i))[2:].encode('utf-8'))
TypeError: object of type 'int' has no len()
```

## Reproduction Steps

```python
import requests

r = requests.Request('PATCH', 'http://domain.com/objects/32', json={'name': 'new name'})
r = r.prepare()

s = requests.Session()
r.prepare_headers({'Authorization': 'Token 123'})
s.send(r)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.6"
  },
  "platform": {
    "release": "4.9.87-linuxkit-aufs",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "1010006f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": false
}
```

**Comment by erayerdin** [comment]
The error occurs while `HTTPAdapter::send` method tries to read the length of `request.body`.

**Comment by sigmavirus24** [comment]
@mlubinmow what do you think should be happening here? I'm not convinced this is a bug in Requests but rather in using undocumented methods.

Specifically http://docs.python-requests.org/en/master/user/advanced/?highlight=PreparedRequest#prepared-requests tells you how you're expected to interact with PreparedRequests and makes no guarantees about the `prepare_*` methods on the object.

**Comment by mlubimow** [comment]
@sigmavirus24 I disagree, function is listed in Devs interface and is inconsistent, as it works for GET request. I would expect it to.. just work ;) As mentioned in an issue.

http://docs.python-requests.org/en/master/api/#lower-lower-level-classes

**Comment by sigmavirus24** [comment]
@mlubimow just because something is included in auto-generated documentation doesn't mean it just magically works as you expect it to.

**Comment by sigmavirus24** [comment]
To be clearer, the documentation I linked to explains how to actually work with the prepared request flow. If something happens to work in one case when you do something the system wasn't designed for, it doesn't mean it must work in a different case.

**Comment by nateprewitt** [comment]
Closing this since it's no longer reproducible since we moved to urllib3's streaming implementation and the original usage wasn't the intent of the method.
